on:
    push:
      branches:
        - main
  
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
  
      - name: Install dependencies
        run: |
          python -m venv /opt/venv
          source /opt/venv/bin/activate
          pip install poetry
          poetry install
  
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
  
      - name: Run Scraper
        run: |
          source /opt/venv/bin/activate
          python scrape.py
      - name: commit files to production
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: scrape
          push_options: '--force'